### ISSUE TITLE
SubOp is not working

### ISSUE THREAD

**Issue by internetKevin** [popupcad/popupcad#100]
The subop appears to not be functional for the latest release. Zhi and I tested it on my Windows10 laptop and the PowerMac in lab. I've attached screenshots of the error box that appears after clicking the "+". Dan - does it work on your computer?

![capture](https://cloud.githubusercontent.com/assets/18147519/14236851/c3457d2c-f9e9-11e5-80d3-f5d70298b30a.PNG)
![capture](https://cloud.githubusercontent.com/assets/18147519/14236835/97e34f56-f9e9-11e5-9a5d-2cdf4fcd2092.PNG)

This is from the log file:
<class 'TypeError'>: row_add_empty() takes 1 positional argument but 2 were given

  File "C:\Users\daukes\code\popupcad\popupcad\widgets\table_common.py", line 108, in row_add_empty

**Comment by danaukes** [comment]
did you download the latest version (3/31) before you tried this? Zhi made
a duplicate bug report last week, which I thought I fixed.  I responded to
him and never heard back.

Please let me know what version you are testing on.

Dan

On Sun, Apr 3, 2016 at 7:19 PM, internetKevin <notifications@github.com>
wrote:

> The subop appears to not be functional for the latest release. Zhi and I
> tested it on my Windows10 laptop and the PowerMac in lab. I've attached
> screenshots of the error box that appears after clicking the "+". Dan -
> does it work on your computer?
>
> [image: capture]
> <https://cloud.githubusercontent.com/assets/18147519/14236851/c3457d2c-f9e9-11e5-80d3-f5d70298b30a.PNG>
> [image: capture]
> <https://cloud.githubusercontent.com/assets/18147519/14236835/97e34f56-f9e9-11e5-9a5d-2cdf4fcd2092.PNG>
>
> This is from the log file:
> : row_add_empty() takes 1 positional argument but 2 were given
>
> File "C:\Users\daukes\code\popupcad\popupcad\widgets\table_common.py",
> line 108, in row_add_empty
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/popupcad/popupcad/issues/100>
>



-- 
Dan Aukes
idealab.asu.edu

Assistant Professor
The Polytechnic School
Fulton Schools of Engineering
Arizona State University

**Comment by internetKevin** [comment]
Okay, I just reinstalled with the latest version. It's working fine now. Thanks!

I was using 3.17.2016 last.
