### ISSUE TITLE
<class 'ImportError'>: No module named "idealab_tools'

### ISSUE THREAD

**Issue by nidlu** [popupcad/popupcad#106]
Edit: I see this has already been a closed issue, although on a mac and installing from source. (thus missed it before posting) I will try installing from source instead, but it'd be nice if it just ran straight out of the box I suppose.
Edit2: Installation from source worked fine.

I'm having trouble running popupCAD on a win10 machine.. I've tried two installs from the msi file on two different windows 10 machines. I receive the following error message:

<class 'ImportError'>: No module named "idealab_tools'

when I:

1. Start the sketcher
2. Make a rectangle
3. Press escape, which, as I understand it, is supposed to let me:
4. Select the rectangle again (soon as I click it, the error message appears).

There are multiple other things that make the message appear, this was just an example that always does it. So I can't change dimensions of the rectangle or anything like that.

I hope this is a simple misunderstanding but I suspect this may be some kind of bug.

**Comment by danaukes** [comment]
Hmm ok I'll try to look at it soon. For now, try an earlier release. That
should work.

Dan

**Comment by danaukes** [comment]
Fixed, please download and check.

**Comment by danaukes** [comment]
okay, it's fixed.  Please see the current revision and check it out.
