### ISSUE TITLE
Magic number error from newest popucad install on anaconda

### ISSUE THREAD

**Issue by nickgravish** [popupcad/popupcad#91]
Running popupcad on anaconda (using exact source created in web documentation) now produces a magic number error in newest version ```9c19e6e```

```
>>> python popupcad.py
Warning: QApplication was created before pyqtgraph was imported; there may be problems (to avoid bugs, call QApplication.setGraphicsSystem("raster") before the QApplication is created).
Traceback (most recent call last):
  File "popupcad.py", line 14, in <module>
    import popupcad
  File "/Users/nickgravish/popupcad/popupcad/__init__.py", line 57, in <module>
    import pypoly2tri
ImportError: bad magic number in 'pypoly2tri': b'\x03\xf3\r\n'
```

Reverting to the previous version I had been using ```38dc47f``` works perfectly with the anaconda install.

**Comment by danaukes** [comment]
hmm, I have removed pypoly2tri since you last installed, and put it on
pip.  I bet the pip version isn't right, because it requires a compile.
you can download and install pypoly2tri separately here
<https://github.com/popupcad/pypoly2tri>

On Mon, Jan 25, 2016 at 9:42 AM, nickgravish <notifications@github.com>
wrote:

> Running popupcad on anaconda (using exact source created in web
> documentation) now produces a magic number error in newest version 9c19e6e
>
> >>> python popupcad.py
> Warning: QApplication was created before pyqtgraph was imported; there may be problems (to avoid bugs, call QApplication.setGraphicsSystem("raster") before the QApplication is created).
> Traceback (most recent call last):
>   File "popupcad.py", line 14, in <module>
>     import popupcad
>   File "/Users/nickgravish/popupcad/popupcad/__init__.py", line 57, in <module>
>     import pypoly2tri
> ImportError: bad magic number in 'pypoly2tri': b'\x03\xf3\r\n'
>
> Reverting to the previous version I had been using 38dc47f works
> perfectly with the anaconda install.
>
> —
> Reply to this email directly or view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_popupcad_popupcad_issues_91&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=yjnTLiBlKr4W189mDVx3e7kaEB8U4ZXO5uHigeERe7g&m=KybZ4w1CwD-QsNR0eLMsso4rVKk34P2pjbrh0yzMEnw&s=IxogWAi1cqY3ZUsEDLxCrtZev2l6XwT5LzeANWROmjg&e=>
> .
>



-- 
Dan Aukes
danaukes@seas.harvard.edu

Please note that my work email address will be changing to danaukes@asu.edu
this winter.  Please update your address book.

**Comment by danaukes** [comment]
issue was caused by multiple installs of pypoly2tri.
