### ISSUE TITLE
Question about constraint updating in API

### ISSUE THREAD

**Issue by nickgravish** [popupcad/popupcad#92]
I have finally gotten around to converting my workflow to popupcad after having manually modified my last set of dxf layers. One thing that I want to do now is to be able to programmatically vary a constraint parameter (I could just programmatically change the points but would like to modify a constraint to get that working) in one of my sketches and then rebuild the drawing and output the cut DXFs. My use case is to make hinges with set stop angles over a fine grade of a single parameter  to dial in a hinge design.

I have spent ~1.5 days in the popupcad code just seeing how everything is laid out, I wanted to do this so that I can contribute when applicable to the project and don't just have to ask you for everything. 

The problem I am having is how to programmatically update sketch geometry after a constraint value is changed. This notebook shows my attempt [here](https://github.com/nickgravish/popupcad/blob/master/api_examples/Popupcad_API_tutorial.ipynb), 

In the notebook I can locate the constraint in the sketch that I want to change. And I can update the constraint value, but I am not sure how best to then update the geometry. I thought the constraintsystem.update() routine would do this. Can you advise how best to update geometry based on changes to the constraints? If we can work this out I am happy to write this up for the API examples.

**Comment by danaukes** [comment]
I will take a look soon and get back to you.  Yes, you're looking in the
right place.  It may take a small piece of code to glue some functionality
together.

**Comment by nickgravish** [comment]
Thanks, I was able to figure out what I needed to do to get this functionality working. The end result is in this [notebook](https://github.com/nickgravish/popupcad/blob/master/api_examples/Popupcad_API_tutorial.ipynb). 

When you get some time we can discuss how to best implements something like this for use. 

Thanks!
Nick

**Comment by danaukes** [comment]
thanks!
