### ISSUE TITLE
Layer Naming

### ISSUE THREAD

**Issue by kjayaram** [popupcad/popupcad#94]
Is there any easy way to change/add the names of materials?

**Comment by nickgravish** [comment]
Kaushik, 

You can change and customize layer names in two ways. 

1) You can edit your `materials.yaml` file to include custom materials that you want to use, these materials are loaded by popupcad every time you run so are always available. The `materials.yaml`
file is located in your popupCAD_files directory. An example file is here with two materials, silicone and fr4
 
```
silicone: !!python/object:popupcad.filetypes.material2.Material2
  E1: 1
  E2: 1
  color: !!python/tuple [0.68359375, 0.31640625, 0.31640625, 0.5]
  density: 1
  id: 43436632
  is_adhesive: true
  is_conductive: false
  is_rigid: false
  name: silicone
  poisson: 0.5
  thickness: 0.025
fr4: !!python/object:popupcad.filetypes.material2.Material2
  E1: 1
  E2: 1
  color: !!python/tuple [1., 1., 0., .5]
  density: 1
  id: 43434840
  is_adhesive: false
  is_conductive: false
  is_rigid: false
  name: fr4
  poisson: 0.5
  thickness: 0.025
```

2) You can dynamically add materials to a CAD file by editing the laminate. To do this select laminate properties from the project menu 

![image](https://cloud.githubusercontent.com/assets/4388231/14078657/adde59b4-f4c5-11e5-921d-363dd0ca7ed8.png)

Select the laminate layer you want to change and then rename it 

![image](https://cloud.githubusercontent.com/assets/4388231/14078677/c593e1fa-f4c5-11e5-892e-70be2aa7151d.png)
 
The name will refresh in the layer names eventually. 

Dan any additional suggestions?

Nick

**Comment by danaukes** [comment]
Nope, just was about to respond, but that works!

Dan

On Mon, Mar 28, 2016 at 6:18 AM, Nick Gravish <notifications@github.com>
wrote:

> Kaushik,
>
> You can change and customize layer names in two ways.
>
> 1) You can edit your materials.yaml file to include custom materials that
> you want to use, these materials are loaded by popupcad every time you run
> so are always available. The materials.yaml
> file is located in your popupCAD_files directory. An example file is here
> with two materials, silicone and fr4
>
> silicone: !!python/object:popupcad.filetypes.material2.Material2
>   E1: 1
>   E2: 1
>   color: !!python/tuple [0.68359375, 0.31640625, 0.31640625, 0.5]
>   density: 1
>   id: 43436632
>   is_adhesive: true
>   is_conductive: false
>   is_rigid: false
>   name: silicone
>   poisson: 0.5
>   thickness: 0.025
> fr4: !!python/object:popupcad.filetypes.material2.Material2
>   E1: 1
>   E2: 1
>   color: !!python/tuple [1., 1., 0., .5]
>   density: 1
>   id: 43434840
>   is_adhesive: false
>   is_conductive: false
>   is_rigid: false
>   name: fr4
>   poisson: 0.5
>   thickness: 0.025
>
> 2) You can dynamically add materials to a CAD file by editing the
> laminate. To do this select laminate properties from the project menu
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/4388231/14078657/adde59b4-f4c5-11e5-921d-363dd0ca7ed8.png>
>
> Select the laminate layer you want to change and then rename it
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/4388231/14078677/c593e1fa-f4c5-11e5-892e-70be2aa7151d.png>
>
> The name will refresh in the layer names eventually.
>
> Dan any additional suggestions?
>
> Nick
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/popupcad/popupcad/issues/94#issuecomment-202388294>
>



-- 
Dan Aukes
idealab.asu.edu

Assistant Professor
The Polytechnic School
Fulton Schools of Engineering
Arizona State University
