### ISSUE TITLE
Script for automated DXF layer importing

### ISSUE THREAD

**Issue by internetKevin** [popupcad/popupcad#96]
This is the script action I'm looking for:

Open a new .CAD file
In the Projects > Sketches functionality, load a DXF. The DXF has multiple layers.
Load each layer of the DXF into its own sketch and have the sketch be the same name as the source layer.
Save the .CAD file.

I can then begin working with the .CAD file once all the layers are imported and renamed.

**Comment by nickgravish** [comment]
Kevin, 

This script should do it. I will send to Dan to add into api_examples. 

https://github.com/nickgravish/popupcad/blob/dxf_import_all_layers/api_examples/dxf_import_all_layers.py

Nick

**Comment by internetKevin** [comment]
It works!!! Thanks Nick!

**Comment by danaukes** [comment]
Thanks for the contribution, I will check it out!

On Tue, Mar 29, 2016 at 2:20 PM, internetKevin <notifications@github.com>
wrote:

> It works!!! Thanks Nick!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/popupcad/popupcad/issues/96#issuecomment-203109966>
>



-- 
Dan Aukes
idealab.asu.edu

Assistant Professor
The Polytechnic School
Fulton Schools of Engineering
Arizona State University

**Comment by danaukes** [comment]
pulled the script in.  Thanks!
