### ISSUE TITLE
Windows Anaconda setup

### ISSUE THREAD

**Issue by internetKevin** [popupcad/popupcad#97]
I installed Anaconda3 4.0.0 for my Win 10, 64-bit machine.
I had to take these steps to get it working right:

- pip install Shapely-1.5.15-cp35-cp35m-win_amd64.whl
- conda install pyqtgraph pyopengl
- pip install pycollada ezdxf pypoly2tri stl

**Comment by internetKevin** [comment]
This was just FYI for future users installing Anaconda to get PopupCAD working on Windows.

**Comment by danaukes** [comment]
Huh, this information was available on popupcad.org but is now missing.  I will see why and fix.

Thanks for the info!

Dan

**Comment by danaukes** [comment]
I updated the website; there were some dead links due to a github change.  Fixed, now there is also some windows anaconda install info on the website.
