### ISSUE TITLE
sub op no longer working

### ISSUE THREAD

**Issue by zhiernteoh** [popupcad/popupcad#98]
![sub op error msg](https://cloud.githubusercontent.com/assets/2783981/14155399/902aeda8-f68f-11e5-82fa-ad7bb645b02a.PNG)

On the latest upgrade, sub op is no longer working

**Comment by danaukes** [comment]
thanks I will try to fix today.

On Wed, Mar 30, 2016 at 12:55 PM, zhiernteoh <notifications@github.com>
wrote:

> [image: sub op error msg]
> <https://cloud.githubusercontent.com/assets/2783981/14155399/902aeda8-f68f-11e5-82fa-ad7bb645b02a.PNG>
>
> On the latest upgrade, sub op is no longer working
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/popupcad/popupcad/issues/98>
>



-- 
Dan Aukes
idealab.asu.edu

Assistant Professor
The Polytechnic School
Fulton Schools of Engineering
Arizona State University

**Comment by danaukes** [comment]
Fixed by ce3950dc2953d80ec8d110e55aad6ed9c7fb271a
